

@URL = https://2dqfj1u70e.execute-api.eu-north-1.amazonaws.com

### Get a user
GET {{URL}}/users/c48c50b0-e958-43ce-95e5-e265dd20ce03

### Create a user
POST {{URL}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com"
}

#### Get all users
GET {{URL}}/users

### Update a user
PUT {{URL}}/users/82b0dca0-2e1d-47be-ad8c-d537f5124828
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com"
}

### Delete a user
DELETE  {{URL}}/users/82b0dca0-2e1d-47be-ad8c-d537f5124828